# this is web group
[frontend]  
frontend.lithesh.shop

# this is app group
[backend] 
backend.lithesh.shop

# this is db group
[db] 
db.lithesh.shop


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321